<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Orion.SharedKernel\Orion.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Application\UseCases\" />
		<Folder Include="Infrastructure\Persistence\Migrations\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Orion.SharedKernel\Orion.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
